# Generated by Django 4.2 on 2023-07-31 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='data',
            new_name='date',
        ),
    ]
